Controllers/CashADvanceController.cs
using CashAdvanceMvC.Models.LogEntity;
using MyApplication.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace CashAdvanceMvC.Controllers
{
    public class CashADvanceController : Controller
    {
        // GET: Employees
        public ActionResult Index()
        {
            IEnumerable<MMvcCashAdvance> empList;
            HttpResponseMessage response = GlobalVariables.WebApiClient.GetAsync("CashAdvances").Result;
            empList = response.Content.ReadAsAsync<IEnumerable<MMvcCashAdvance>>().Result;

           // return Json(new { data = empList }, JsonRequestBehavior.AllowGet);
           return View(empList);
        }
        // GET: Employees
        public ActionResult AddorEdit(int id=0)
        {
            if(id==0)
            {
              
            return View(new MMvcCashAdvance());
            }

            using(CashAdvanceDbEntities db = new CashAdvanceDbEntities())
            {

            HttpResponseMessage response = GlobalVariables.WebApiClient.GetAsync("CashAdvances/" + id.ToString()).Result;
            var res = response.Content.ReadAsAsync<MMvcCashAdvance>().Result;
            res.approvedBY = Session["HODName"].ToString();


            var empl = db.DbEmployees.FirstOrDefault(x=> x.Name == res.requestBy);
                res.Employee_Id = empl.Id;


            HttpResponseMessage result = GlobalVariables.WebApiClient.PutAsJsonAsync("CashAdvances/"+ res.Id, res).Result;

            }

            //  HttpResponseMessage response = GlobalVariables.WebApiClient.PutAsJsonAsync("CashAdvances", id).Result;
         //   HttpResponseMessage response = GlobalVariables.WebApiClient.PostAsJsonAsync("CashAdvances", res).Result;
            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult AddorEditPost(MMvcCashAdvance emp)
        {
            var amount = Convert.ToInt32(emp.amount);
            
            if (emp.Id> 0)
            {
               
                _= GlobalVariables.WebApiClient.PutAsJsonAsync("CashAdvances", emp).Result;

                return View("Index");

            }
            if(amount < 50001)
            {

                emp.department = Session["Department"].ToString();
                emp.requestBy = Session["Name"].ToString();

                HttpResponseMessage response = GlobalVariables.WebApiClient.PostAsJsonAsync("CashAdvances", emp).Result;

        
                emp.LOginErrorMessage = "Request Successfully Submitted";
           

                    ViewBag.message = "RequesT Successfully Submitted";
                    return View("Successfull", emp);

            }
            else
            {

                emp.LOginErrorMessage = "Your Limitation has been Exceeded";


                return View("AddorEdit", emp);
            }
           
        }
        public ActionResult Successfull()
        {
            return View();
        }
        [HttpPut]
        public ActionResult Approve
        (MMvcCashAdvance emp)
        {
            HttpResponseMessage response = GlobalVariables.WebApiClient.PutAsJsonAsync("CashAdvances", emp).Result;
            // var res = response.Content.ReadAsAsync<MMvcCashAdvance>().Result;
            return RedirectToAction("Index");
        }
    }

       
    
}

Views/Update/Approved.cshtml
@model MyApplication.Models.MMvcCashAdvance

@{
    ViewBag.Title = "Approved";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Approved</h2>




@using (Html.BeginForm("AddorEditPost", "CashADvance", FormMethod.Post))
{
    @Html.AntiForgeryToken()



    <div class="form-horizontal">
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.requestBy)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.requestBy)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.requestDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.requestDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.approvedDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.approvedDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.approvedBY)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.approvedBY)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.requestStatus)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.requestStatus)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Employee_Id)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Employee_Id)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.amount)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.amount)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.department)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.department)
            </dd>

        </dl>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Update/Approved1.cshtml
@model MyApplication.Models.MMvcCashAdvance

@{
    ViewBag.Title = "Approved1";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Approved1</h2>

<div>
    <h4>MMvcCashAdvance</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.requestBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.requestBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.requestDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.requestDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.approvedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.approvedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.approvedBY)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.approvedBY)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.requestStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.requestStatus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Employee_Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employee_Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.amount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.amount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.department)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.department)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>